name: "Push notification on Whatsapp with custom messages"
description: "Triggers a Private Message to the specified Whatsapp forked from https://github.com/ishween/whatsapp-push-notify-action"
author: "Ishween Kaur"
branding:
  icon: message-square
  color: blue
